// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timer.proto

/*
Package timer is a generated protocol buffer package.

It is generated from these files:
	timer.proto

It has these top-level messages:
	TimeRequest
	TimeResponse
*/
package timer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TimeRequest struct {
}

func (m *TimeRequest) Reset()                    { *m = TimeRequest{} }
func (m *TimeRequest) String() string            { return proto.CompactTextString(m) }
func (*TimeRequest) ProtoMessage()               {}
func (*TimeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TimeResponse struct {
	Time string `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
}

func (m *TimeResponse) Reset()                    { *m = TimeResponse{} }
func (m *TimeResponse) String() string            { return proto.CompactTextString(m) }
func (*TimeResponse) ProtoMessage()               {}
func (*TimeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TimeResponse) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func init() {
	proto.RegisterType((*TimeRequest)(nil), "timer.TimeRequest")
	proto.RegisterType((*TimeResponse)(nil), "timer.TimeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Timer service

type TimerClient interface {
	Timer(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (Timer_TimerClient, error)
}

type timerClient struct {
	cc *grpc.ClientConn
}

func NewTimerClient(cc *grpc.ClientConn) TimerClient {
	return &timerClient{cc}
}

func (c *timerClient) Timer(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (Timer_TimerClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Timer_serviceDesc.Streams[0], c.cc, "/timer.Timer/Timer", opts...)
	if err != nil {
		return nil, err
	}
	x := &timerTimerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Timer_TimerClient interface {
	Recv() (*TimeResponse, error)
	grpc.ClientStream
}

type timerTimerClient struct {
	grpc.ClientStream
}

func (x *timerTimerClient) Recv() (*TimeResponse, error) {
	m := new(TimeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Timer service

type TimerServer interface {
	Timer(*TimeRequest, Timer_TimerServer) error
}

func RegisterTimerServer(s *grpc.Server, srv TimerServer) {
	s.RegisterService(&_Timer_serviceDesc, srv)
}

func _Timer_Timer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TimeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TimerServer).Timer(m, &timerTimerServer{stream})
}

type Timer_TimerServer interface {
	Send(*TimeResponse) error
	grpc.ServerStream
}

type timerTimerServer struct {
	grpc.ServerStream
}

func (x *timerTimerServer) Send(m *TimeResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Timer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "timer.Timer",
	HandlerType: (*TimerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Timer",
			Handler:       _Timer_Timer_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "timer.proto",
}

func init() { proto.RegisterFile("timer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xc9, 0xcc, 0x4d,
	0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x78, 0xb9, 0xb8, 0x43,
	0x32, 0x73, 0x53, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x94, 0x94, 0xb8, 0x78, 0x20, 0xdc,
	0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x21, 0x2e, 0x16, 0x90, 0x3a, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x30, 0xdb, 0xc8, 0x96, 0x8b, 0x15, 0xa4, 0xa6, 0x48, 0xc8, 0x04, 0xc6, 0x10,
	0xd2, 0x83, 0x98, 0x8c, 0x64, 0x92, 0x94, 0x30, 0x8a, 0x18, 0xc4, 0x38, 0x25, 0x06, 0x03, 0x46,
	0x27, 0x03, 0x2e, 0x85, 0xe4, 0xfc, 0x5c, 0xbd, 0xc4, 0xbc, 0xd2, 0x82, 0xe4, 0xfc, 0xf2, 0xec,
	0xd2, 0x22, 0xbd, 0xf4, 0xa2, 0x82, 0xe4, 0xf8, 0x94, 0xd4, 0xdc, 0xfc, 0xf8, 0xc4, 0xbc, 0x94,
	0xa2, 0xfc, 0xcc, 0x14, 0x27, 0x2e, 0xb0, 0xb9, 0x01, 0x20, 0x87, 0x06, 0x30, 0x26, 0xb1, 0x81,
	0x5d, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x29, 0x10, 0x28, 0xca, 0xc0, 0x00, 0x00, 0x00,
}
